import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Navbar } from "../components/mini-navbar";

import { StarsBackground } from "../components/stars"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StarsBackground className="min-h-screen w-full">
          <div className="pt-22">
            {children}
          </div>
        </StarsBackground>
      </body>
  </html>
);
}